{{- if .Values.frontend.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "soba.fullname" . }}
  labels: {{- include "soba.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $val := .Values.frontend.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  host: {{ include "soba.fullname" . }}.{{ .Values.global.domain }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ include "soba.fullname" . }}-frontend
    weight: 100
{{- end }}
